services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_RUNTIME_ENVIRONMENT="production"
      - EXPRESS_API_ADMIN_KEY=${EXPRESS_API_ADMIN_KEY}
    depends_on:
      - db

  nuxt-app:
    build: ./nuxt-app
    ports:
      - "3000:3000"
    environment:
      - NUXT_DB_HOST=${DB_HOST}
      - NUXT_DB_USER=${DB_USER}
      - NUXT_DB_PASSWORD=${DB_PASSWORD}
      - NUXT_DB_DATABASE=${DB_NAME}
      - NUXT_PUBLIC_FIREBASE_API_KEY=${PUBLIC_FIREBASE_API_KEY}
      - NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NUXT_PUBLIC_FIREBASE_PROJECT_ID=${PUBLIC_FIREBASE_PROJECT_ID}
      - NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NUXT_PUBLIC_FIREBASE_APP_ID=${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${PUBLIC_FIREBASE_MEASUREMENT_ID}
      - NUXT_FIREBASE_ADMIN_TYPE=${FIREBASE_ADMIN_TYPE}
      - NUXT_FIREBASE_ADMIN_PROJECT_ID=${FIREBASE_ADMIN_PROJECT_ID}
      - NUXT_FIREBASE_ADMIN_PRIVATE_KEY_ID=${FIREBASE_ADMIN_PRIVATE_KEY_ID}
      - NUXT_FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
      - NUXT_FIREBASE_ADMIN_CLIENT_EMAIL=${FIREBASE_ADMIN_CLIENT_EMAIL}
      - NUXT_FIREBASE_ADMIN_CLIENT_ID=${FIREBASE_ADMIN_CLIENT_ID}
      - NUXT_FIREBASE_ADMIN_AUTH_URI=${FIREBASE_ADMIN_AUTH_URI}
      - NUXT_FIREBASE_ADMIN_TOKEN_URI=${FIREBASE_ADMIN_TOKEN_URI}
      - NUXT_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL}
      - NUXT_FIREBASE_ADMIN_CLIENT_X509_CERT_URL=${FIREBASE_ADMIN_CLIENT_X509_CERT_URL}
      - NUXT_FIREBASE_ADMIN_UNIVERSE_DOMAIN=${FIREBASE_ADMIN_UNIVERSE_DOMAIN}
      - NUXT_EXPRESS_ADMIN_KEY=${EXPRESS_API_ADMIN_KEY}
      - NUXT_EXPRESS_HOST="api"
      - NUXT_EXPRESS_PORT=8080
    depends_on:
      - db

  db:
    image: mysql:9.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - prompt_base:/var/lib/mysql

volumes:
  prompt_base: {}